# Generated by Django 4.2.7 on 2023-11-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="campus",
            field=models.CharField(
                choices=[
                    ("AL", "Abelardo Luz "),
                    ("AR", "Araquari"),
                    ("BL", "Blumenau"),
                    ("BR", "Brusque"),
                    ("CA", "Camboriú"),
                    ("CO", "Concórdia"),
                    ("FR", "Fraiburgo "),
                    ("IB", "Ibirama"),
                    ("LU", "Luzerna"),
                    ("RS", "Rio do Sul "),
                    ("CA", "Camboriú"),
                    ("SR", "Santa Rosa do Sul"),
                    ("SB", "São Bento do Sul"),
                    ("SF", "São Francisco do Sul"),
                    ("SO", "Sombrio "),
                    ("VI", "Videira"),
                ],
                default="AL",
                max_length=2,
            ),
        ),
    ]
